version: "3.9"
services:
  web:
    container_name: covid-19-tracker-server
    image: covid-19-tracker-server
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3.96.166.222:8080:8080"
    env_file:
      - ./.env


