version: "3.9"
services:
  web:
    container_name: covid-19-tracker-server
    image: covid-19-tracker-server
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

