name:  CI - PR/Merge to Master

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Create .env file
    - name: Create .env file
      env:
        DEV_ENV: ${{ secrets.DEV_ENV }}
      run: echo $DEV_ENV | base64 --decode > .env
        
    - name: Build docker image
      run: docker-compose build

    - name: Run docker container
      run: docker-compose up -d
      
    - name: Run tests
      run: docker exec covid-19-tracker-server npm run test --verbose
